options:
  auto-update: true
mobs:
- BLAZE
- CAVE_SPIDER
- CHICKEN
- COW
- CREEPER
- DROWNED
- EVOKER
- ENDERMAN
- ENDERMITE
- FOX
- GHAST
- GUARDIAN
- HORSE
- HUSK
- ILLUSIONER
- IRON_GOLEM
- LLAMA
- MAGMA_CUBE
- MUSHROOM_COW
- OCELOT
- PANDA
- PARROT
- PHANTOM
- PIG
- PIG_ZOMBIE
- PILLAGER
- POLAR_BEAR
- RABBIT
- RAVAGER
- SHEEP
- SILVERFISH
- SKELETON
- SLIME
- SPIDER
- SQUID
- STRAY
- VILLAGER
- VINDICATOR
- WITCH
- WITHER_SKELETON
- WOLF
- ZOMBIE
- ZOMBIE_VILLAGER
- ZOMBIFIED_PIGLIN