required-souls: 128
mobs:
- BLAZE
- CAVE_SPIDER
- CHICKEN
- COW
- CREEPER
- ENDERMAN
- ENDERMITE
- GHAST
- GUARDIAN
- HORSE
- IRON_GOLEM
- MAGMA_CUBE
- MUSHROOM_COW
- OCELOT
- PIG
- PIG_ZOMBIE
- RABBIT
- SHEEP
- SILVERFISH
- SKELETON
- SLIME
- SPIDER
- SQUID
- VILLAGER
- WITCH
- WOLF
- ZOMBIE
